on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Unit_Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Tests in Development Container
        uses: devcontainers/ci@v0.3
        with:
          runCmd: bun test
          push: never

  Build_Code:
    needs: Unit_Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build the code
        run: bun run bundle.ts

      - name: Get version from package.json
        id: version
        run: |
          VERSION=$(bun -p "require('./package.json').version")
          echo "Version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Create a new tag (if needed)
        run: |
          git tag "v${{ env.version }}"
          git push origin "v${{ env.version }}"

      - name: Create or Update GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ env.version }}"
          name: "Release ${{ env.version }}"
          body: |
            ## Release details
            This release includes the latest build for version ${{ env.version }}.
          files: dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
