on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Unit_Tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node (for bun)
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      # Step 3: Install dependencies
      - name: Install dependencies
        run: bun install

      # Step 4: Run Tests
      - name: Build the code
        run: bun test

  Build_Code:
    needs: Unit_Tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node (for bun)
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      # Step 3: Install dependencies
      - name: Install dependencies
        run: bun install

      # Step 4: Run bundling
      - name: Build the code
        run: bun run bundle.ts

      # Step 5: Create GitHub release
      - name: Easy Github Release
        uses: misha-brt/create-release@v0.0.1
        with:
          # A GitHub API token
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: release
