on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup and Use Development Container
      - name: Run Tests in Development Container
        uses: devcontainers/ci@v0.3
        with:
          runCmd: bun test
          push: never
